POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name":"prueba",
    "email": "elaflores@gmail.com",
    "password":"123456"

}

### login sin conexion a db

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "elaflores@gmail.com",
    "password":"123456",
    "name": "prueba2"
}

### users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MzA2NTI1ODAsImV4cCI6MTczMDY1MjY0MH0.6I7OeAEB4GD5u-DIMTtSXMvpgSaaatktqee7lWAScH4